<!DOCTYPE html>
<html>
    <head>

   	<meta charset="utf-8" />   
   	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<title>{{ title }}</title>

	<meta name="description" content="" />
	<meta property="og:site_name" content="" /> 

    <!-- CSS -->
    {{ assets.outputCss() }}

    </head>
    <body>

    <!-- JS -->
    {{ assets.outputJs() }}

        <div class="pageContent">

            <header>

            </header>

            <div class="content">
                <div class="newForm login">
                <h3>Login</h3>
                {{ form("login/start", "method": "post") }}
                <div class="row">
                    <div class="small-6 columns">
                        <label for="email">Username<small>required</small>
                        <?php echo $this->tag->textField(array("username", "size" => "30")) ?>
                    </label>
                    </div>
                </div>

                <div class="row">
                    <div class="small-6 columns">
                        <label for="password">Password<small>required</small>
                        <?php echo $this->tag->passwordField(array("password", "size" => "30")) ?>
                    </label>
                    </div>
                </div>
                <div class="row">
                    <?php $this->flashSession->output() ?>
                </div>
                {{ submit_button('login') }} 
                </form>
                </div>  
            </div>
        </div>

    </body>
</html>